openapi: 3.0.3
info:
  title: 'API'
  version: '1.0.0'
  description: 'API'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: 'API Support'
    url: 'http://www.swagger.io/support'
servers:
  - url: 'https://api.server.test/v1'
    description: Server description
paths: 
  /clubs:
     get:
      tags:
        - clubs
      summary: Get all clubs
      description: Get all clubs
      operationId: getClubs
      parameters:
        - name: page
          in: query
          description: page number
          required: false
          schema:
            type: integer
            format: int32
          example: 1
            
        - name: per_page
          in: query
          description: number of items per page
          required: false
          schema:
            type: integer
            format: int32
          example: 10
          
      responses:
        '200':
          description: A list of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
        '400':
          description: Invalid page number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  #add security schemes with apiKey
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Club:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Pagination:
      type: object
      properties:
        total:
          type: integer
          format: int32
        per_page:
          type: integer
          format: int32
        current_page:
          type: integer
          format: int32
        last_page:
          type: integer
          format: int32
        next_page_url:
          type: string
        prev_page_url:
          type: string
        from:
          type: integer
          format: int32
        to:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: '#/components/schemas/Club'
